

services:
  app:
    image: weatherforecastapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
      - redis

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "weatherforecastdb"
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  redis-data: